version: '3.8'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://wateradventure:wateradventure@db:5432/wateradventure?schema=public
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - /app/.svelte-kit

  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=wateradventure
      - POSTGRES_PASSWORD=wateradventure
      - POSTGRES_DB=wateradventure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wateradventure"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: